---

  #install auditd package
- name: install auditd package | package-08
  package:
    name: '{{ auditd_package }}'
    state: 'present'

  #configure auditd 
- name: configure auditd | package-08
  template:
    src: 'auditd.conf.j2'
    dest: '/etc/audit/auditd.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'
