# the reason for this is so a user cannot connect to a server,
# that isn't connected to an LDAP server anymore.
# normally caching credentials shouldn't be necessary for most machines.
# removing it provides some more security while not removing usability.
  # remove pam ccreds
- name: remove pam ccreds to disable password caching
  package:
    name: '{{ os_packages_pam_ccreds }}'
    state: 'absent'
  
  #remove passwdqc
- name: remove passwdqc
  yum:
    name: '{{ os_packages_pam_passwdqc }}'
    state: 'absent'
  when:
    - ansible_facts.os_family == 'RedHat'
    - not os_auth_pam_passwdqc_enable

    
  #configure passwdqc and tally  
- name: configure passwdqc and tally via central system-auth confic
  template:
    src: 'rhel_system_auth.j2'
    dest: '/etc/pam.d/system-auth-ac'
    mode: '0640'
    owner: 'root'
    group: 'root'
  when: ansible_facts.os_family == 'RedHat'

    #Gather package facts
  - name: Gather package facts
  package_facts:
    manager: auto
    
  #Upgrade Password Hashing Algorithm to SHA-512
- name: NSA 2.3.3.5 Upgrade Password Hashing Algorithm to SHA-512
  template:
    src: 'libuser.conf.j2'
    dest: '/etc/libuser.conf'
    mode: '0640'
    owner: 'root'
    group: 'root'
  when: "'libuser' in ansible_facts.packages"
